#!/bin/sh
xrandr --output eDP1 --off --output DP1 --mode 3840x2160 --pos 0x0 --rotate normal --output DP2 --off --output HDMI1 --off --output HDMI2 --mode 1920x1080 --pos 3840x120 --rotate right --output VIRTUAL1 --off
