#!/bin/sh
xrandr --output eDP-1 --off --output DP-1 --primary --mode 3840x2160 --pos 0x0 --rotate normal --output HDMI-1 --off --output DP-2 --off --output HDMI-2 --mode 1920x1080 --pos 3840x120 --rotate right
